### PR TITLE
Fix categories layout (task #1662)

### PR DESCRIPTION
**Pull request by flangofas**
Snapshot of index action
image

### CODE REVIEW

**Comment by sioannides** [comment]
:+1:

**Comment by georgeconstantinou** [comment]
:+1:

**Comment by mamchenkov** [comment]
@flangofas in the screenshot, Name and Node are the same .. just one is indented and one is not ... leave the indented one and rename it to Name ... please drop Name and Slug as well ;)

**Comment by flangofas** [comment]
@mamchenkov done.

**Pull request merged**
